### ISSUE TITLE
Contrat d'apprentissage

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#567]
> les amis, il va falloir penser aux apprentis, https://www.lapprenti.com/html/apprenti/salaire_cotisations.asp
On me dit d'un côté "apprenti = 0 charges (net = brut), super simple, rémun min = coeff (age) * SMIC, et des sons de clôche different comme ici <https://www.urssaf.fr/portail/home/employeur/beneficier-dune-exoneration/exonerations-ou-aides-liees-a-la/le-contrat-dapprentissage.html>
le sujet est politique, il mérite une entrée de haut niveau "le salaire d'un employé" "le salaire d'un apprenti"
<sub>[View in Slack](https://startups-detat.slack.com/archives/C07JG3R33/p1560435179004600)</sub>
@ppezziardi 

Une réforme des contrats d’apprentissage est entrée en vigueur en début d'année. Après une recherche rapide il semble que les règles à intégrer sont :

* Exonérations des cotisations salariales jusqu'à 79% du SMIC (1202€)
* Exonération de CSG/CRDS en totalité
* Exonération d'IR dans la limite d'un SMIC (comme pour les gratifications de stages, cf #563)

**Comment by johangirod** [comment]
*@laem : *
> https://www.alternance.emploi.gouv.fr/portail_alternance/jcms/gc_5504/simulateur-employeur
> Il correspond bien au besoin des employeurs d'après @ppezziardi , et ça permettrait d'enrichir la page /sécurité-sociale avec un lien juste en-dessous du salarié : "simuler le salaire et les aides d'un alternant"

**Comment by johangirod** [comment]
Je rejoint @laem, si le sujet est couvert par un autre simulateur qui fait le taf', on peut l'ajouter sur la page sécurité sociale ou mieux, via un lien discret sur la page embauche ('vous cherchez un simulateur pour alternant ?")

**Comment by mquandalle** [comment]
@johangirod Les deux simulateurs sont complémentaires non ? Celui du portail alternance donne la rémunération en brut à partir de l'âge de l'apprenti, type de formation, etc. mais ne calcule pas les cotisations et impôts sur cette rémunération brute.
Donc ça serait bien de le référencer, et en plus d'intégrer les exonérations de cotis et d'IR sur le simulateur d'embauche.

**Comment by johangirod** [comment]
Effectivement, je suis allé un peu vite. Je suis d'accord, au moyen terme, on intègrera le sujet directement dans nos règles. Mais le besoin des usagers reste le même, peu importe la solution, d'où l'idée de rassembler les discussions dans une seule issue (quitte à avoir différentes PR qui s'y rapportent).

**Comment by mquandalle** [comment]
J'ai commencé à implémenter les exonérations pour les apprentis, l'exonération d'IR ne pose pas de problèmes (c'est la même que pour les gratifications de stage), je suis en revanche perplexe sur l'implémentation de l'exonération de cotisations sociales.

Celle-ci consiste en un abattement (de 79% du SMIC) sur l'assiette des cotisations salaries, et uniquement sur la partie salariale. Dans la base de règles les cotisations sont pour l'instant définies avec deux composantes (salariale et patronale) et une assiette unique, @johangirod @laem avez-vous une opinion sur la manière de gérer deux assiettes différentes sur ces deux composantes ?

**Comment by laem** [comment]
J'ai l'impression que le simulateur fait le calcul des cotisations sociales non ?

![Screenshot_20190702-170556_Kiwi Browser](https://user-images.githubusercontent.com/1177762/60523821-b639ce00-9ceb-11e9-811d-efc28b78e501.jpg)

**Comment by mquandalle** [comment]
Ah oui tiens (j'ai du regarder un peu vite sur mon téléphone), mais sur c'est uniquement les cotisations patronales, non ?

**Comment by laem** [comment]
Oui mais tu as aussi un mode "je suis un alternant", qui j'imagine présente le net après cotisations.

**Comment by mquandalle** [comment]
Non, c'est brut uniquement :

![Portail de l'Alternance](https://user-images.githubusercontent.com/1730702/60526954-a0c7a280-9cf1-11e9-9132-10fceaba7cf9.png)

**Comment by mquandalle** [comment]
Une solution pour la description des règles de l'apprentissage (base des cotisations différente pour la partie patronale et salariale) est de modifier le mécanisme `multiplication` pour qu'elle se fasse `composante` par composante, l'assiette des cotisations s'écrirait ensuite :

```yaml
- espace: contrat salarié . cotisations
  nom: assiette
  titre: Assiette des cotisations sociales
  formule:
    variations:
      - si: contrat . apprentissage
        alors:
          composantes:
            - attributs:
                dû par: employeur
              assiette: base
            - attributs:
                dû par: salarié
              assiette:
                allègement:
                  assiette: base
                  abattement: 79% * SMIC
      - sinon: base

- espace: contrat salarié . cotisations . assiette
  nom: base
  formule: rémunération . brut - indemnité kilométrique vélo
```
