### ISSUE TITLE
Juxtaposition des règles concernant les régimes d'exceptions

### ISSUE THREAD

**Issue by mquandalle** [betagouv/syso#591]
La spécifications des exonérations de régimes comme le régime des impatriés, celui de l'assimilé salarié, le statut JEI ou encore des gratifications de stage est actuellement éparpillée dans tous le fichier `base.yaml` sous la forme de multiple instructions `non applicable si` sur les règles exonérées.

Une alternative serait de définir l'ensemble des exonérations au niveau de la définition du régime :

```yaml
nom: stage
exonérations:
  - réduction générale
  - contribution d'équilibre général
  - retraite complémentaire
  - chômage
  - complémentaire santé
  - contribution au dialogue social
  - statut JEI
```

Cette approche serait plus en phase avec la manière dont les règles sont définies dans la loi et les textes réglementaires (c'est lorsque l'on parle du régime des impatriés que l'on précise l'exonération de cotisations pour la retraite complémentaire, plutôt que quand on parle de la retraite complémentaire que l'on liste les cas où elle ne s'applique pas). Cela permet aussi d'avoir une juxtaposition de toutes les règles définissant un régime d'exception (niche fiscale, etc.) plutôt que d'avoir ces caractéristiques éclatées comme des exceptions des règles générales.

Le mécanisme `non applicable si` resterait utile pour les exclusions du type :

```yaml
nom: réduction générale
non applicable si: cotisations . assiette > plafond de l'assiette
```

ou

```yaml
nom: contribution supplémentaire à l'apprentissage
non applicable si:
  une de ces conditions:
    - entreprise . effectif < 250
    - entreprise . ratio alternants >= 5%
```

Ici il ne s'agit pas d'exceptions mais bien de conditions d'application du dispositif qui sont générales.

**Comment by mquandalle** [comment]
J'ai commencé à regarder l'implémentation de cette fonctionnalité, mais j'ai du mal à m'y retrouver dans le moteur. On peut en discuter lundi @laem ?

Modifs par rapport aux exemples ci-dessus :

* utiliser `non applicable` au lieu de `exonérations` :

    ```yaml
    nom: assimilé salarié
    non applicable:
    - réduction générale
    - AGS
    - statut Cadre 
    - statut JEI
    ```

* le mécanisme `non applicable si` devient inutile dans la grande majorité des cas, en effet il ne reste utilisé que pour des conditions d'applicabilités qui peuvent être plus clairement décrites avec `applicable si`
